spring:
  application:
    name: FlashCard
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: "jdbc:mysql://localhost:3306/vocalearn_demo_db"
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          characterEncoding: utf-8
          useUnicode: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: qdao10122003badao@gmail.com
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
  cache:
    type: redis

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: Y2FyZW1hbGxvd2lzYXZlcnljb21wbGV4c2VjcmV0a2V5dGhhdGlzdmVyeWhhcmR0b2d1ZXNz
  accessTokenExpiration: 86400000
  renewalTokenExpiration: 604800000

digitalocean:
  space:
    endpoint: https://flashcard-space.sgp1.digitaloceanspaces.com
    access-key: DO009DMV2WZMZFCLY7NZ
    secret-key: k85ynp9BF5UBH/F2H8/wNIA9qfECDq2y3rJkrAJxED4
    name: flashcard-space
    region: sgp1

minio:
  endpoint: http://minio:9000
  public-endpoint: http://localhost:9000
  access-key: "${MINIO_ACCESS_KEY:123}"
  secret-key: "${MINIO_SECRET_KEY:123}"
  bucket: "${MINIO_BUCKET:haha}"

vnpay:
  tmnCode: "${VNPAY_TMN_CODE:xxx}"
  hashSecret: "${VNPAY_HASH_SECRET:xx}"
  url: "${VNPAY_URL:xx}"
  returnUrl: "${VNPAY_RETURN_URL:xx}"
  ipn: "${VNPAY_IPN:https://nontenurially-reemergent-gabriel.ngrok-free.dev/api/payment/vnpay-ipn}"

logging:
  level:
    "software.amazon.awssdk.request": DEBUG
    "software.amazon.awssdk.auth": DEBUG
    "org.springframework.web": DEBUG
    "com.fasterxml.jackson": DEBUG
